name: Deploy Next.js to Nginx Server

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build Next.js application
        run: yarn build

      - name: Archive build artifacts
        run: tar -czf build.tar.gz .next public package.json yarn.lock

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-build
          path: build.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: nextjs-build
          path: ./build

      # - name: Transfer build artifact to server
      #   uses: appleboy/scp-action@v0.1.7
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     password: ${{ secrets.SERVER_PASSWORD }}
      #     source: ./build/build.tar.gz
      #     target: /var/www/startup/TestGarageEcommerce/

      # - name: Verify Build on Server
      #   uses: appleboy/ssh-action@v0.1.5
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     password: ${{ secrets.SERVER_PASSWORD }}
      #     script: |
      #       ls -l /var/www/startup/TestGarageEcommerce/build.tar.gz
      # - name: Verify Extracted Files
      #   uses: appleboy/ssh-action@v0.1.5
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     password: ${{ secrets.SERVER_PASSWORD }}
      #     script: |
      #       cd /var/www/startup/TestGarageEcommerce
      #       ls -l

      - name: Deploy and reload PM2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /var/www/startup/TestGarageEcommerces
            tar -xzf build.tar.gz
            yarn install --production
            yarn build
            pm2 restart TestGarageWebApi
