name: web.

on:
  push:
    tag:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build Next.js application
        run: yarn build

      - name: Archive build artifacts
        run: tar -czf build.tar.gz .next public package.json yarn.lock

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-build
          path: build.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: nextjs-build
          path: ./build

      - name: Deploy and reload PM2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /var/www/startup/GarageEcommerce
            git pull origin main
            yarn 
            yarn build
            pm2 restart GarageWebApi
